export const admin = {
  metadataTitle: 'Admin',
  navLabel: 'Admin',
  nav: {
    overview: 'Overview',
    requests: 'Requests',
    consultations: 'Consultations',
    slots: 'Slots',
    articles: 'Articles',
    whatsapp: 'WhatsApp',
    users: 'Users',
  },
  pageTitles: {
    overview: 'Overview',
    requests: 'Requests',
    request: 'Request',
    consultations: 'Consultations',
    slots: 'Slots',
    articles: 'Articles',
    newArticle: 'New article',
    editArticle: 'Edit article',
    whatsapp: 'WhatsApp assistant',
    whatsappContact: 'WhatsApp conversation',
    users: 'Users',
  },

  accessNotice: {
    title: 'Admin access required',
    body: 'This account isn’t an admin. Sign in with an admin email.',
    cta: 'Go to My LexBridge',
  },

  common: {
    status: 'Status',
    allStatuses: 'All statuses',
    search: 'Search',
    apply: 'Apply',
    saving: 'Saving…',
    notProvided: 'Not provided',
    none: 'None',
  },

  overview: {
    title: 'Overview',
    description: 'What needs attention today.',
    openRequests: 'Open requests',
    upcomingConsultations: 'Upcoming consultations',
    openSlots: 'Open slots',
    publishedArticles: 'Published articles',
    requestsByStatus: 'Requests by status',
  },

  requests: {
    title: 'Service requests',
    description: 'Everything submitted through the website.',
    service: 'Service',
    allServices: 'All services',
    searchPlaceholder: 'Reference, name, email or phone',
    searchHint: 'Start of reference or email, last phone digits, or whole name words.',
    empty: 'No requests match these filters.',
    count: (total) => `${total} ${total === 1 ? 'request' : 'requests'}`,
    updating: ', updating…',
    columns: {
      reference: 'Reference',
      client: 'Client',
      service: 'Service',
      status: 'Status',
      assigned: 'Assigned',
      received: 'Received',
    },
    unassigned: 'Unassigned',
  },

  requestDetail: {
    breadcrumb: 'Requests',
    notFound: (referenceCode) => `No request found with reference ${referenceCode}.`,
    back: 'Back to requests',
    meta: (serviceLabel, receivedLabel, sourceLabel) => `${serviceLabel}. Received ${receivedLabel} via ${sourceLabel}.`,
    saved: 'Request updated.',
    clientTitle: 'Client',
    name: 'Name',
    email: 'Email',
    phone: 'Phone',
    whatsApp: 'WhatsApp updates',
    optedIn: 'Opted in',
    notOptedIn: 'Not opted in',
    openChat: 'Open chat',
    chatGreeting: (fullName, referenceCode) => `Hello ${fullName}, this is LexBridge about your request ${referenceCode}.`,
    consent: 'Consent recorded',
    no: 'No',
    account: 'Account',
    linkedAccount: 'Linked to an account',
    guest: 'Sent without signing in',
    requirement: 'Requirement',
    history: 'History',
    documents: 'Documents',
    noDocuments: 'No documents yet.',
    shareTitle: 'Share with client',
    shareSubmit: 'Upload and share',
    update: {
      title: 'Update request',
      note: 'Note for client',
      noteHint: 'Shown in My LexBridge. Leave empty for internal changes.',
      assignedTo: 'Assigned to',
      nothingChanged: 'Change the status, add a note or reassign first.',
      save: 'Save update',
    },
  },

  consultations: {
    title: 'Consultations',
    description: 'Bookings in date order. Open one to update it.',
    empty: 'No consultations match.',
    when: (dayLabel, timeLabel) => `${dayLabel}, ${timeLabel} IST`,
    summary: (clientLabel, typeLabel, modeLabel, referenceCode) => `${clientLabel}, ${typeLabel}, ${modeLabel}, ${referenceCode}`,
    clientFallback: 'Client',
    email: 'Email',
    notAvailable: 'Not available',
    phone: 'Booking phone',
    booked: 'Booked',
    duration: 'Duration',
    minutes: (minutes) => `${minutes} minutes`,
    whatsApp: 'WhatsApp updates',
    optedIn: 'Opted in',
    notOptedIn: 'Not opted in',
    editor: {
      statusHint: 'Cancelling frees the slot.',
      meetingLink: 'Meeting link',
      videoOnly: '(video only)',
      meetingPlaceholder: 'https://meet.google.com/…',
      meetingHint: 'Shown to the client.',
      note: 'Internal note',
      nothingChanged: 'Nothing has changed.',
      saved: 'Consultation updated.',
      save: 'Save changes',
    },
  },

  slots: {
    title: 'Consultation slots',
    description: 'Times clients can book. All in IST.',
    listLabel: 'Scheduled slots',
    empty: 'No slots yet. Add some so clients can book.',
    durationShort: (minutes) => `${minutes} min`,
    delete: 'Delete',
    deleting: 'Deleting…',
    deleteLabel: (timeLabel, dayLabel) => `Delete ${timeLabel} slot on ${dayLabel}`,
    create: {
      title: 'Open new slots',
      date: 'Date',
      times: 'Start times (IST, 24-hour)',
      timesPlaceholder: '10:00, 11:00, 15:30',
      timesHint: 'Separate with commas or spaces.',
      duration: 'Duration',
      minutes: (minutes) => `${minutes} minutes`,
      chooseDate: 'Choose a date.',
      invalidTimes: (times) => `Use 24-hour times like 10:00. Check: ${times}.`,
      addTime: 'Add at least one start time.',
      added: (created, skipped) =>
        `${created} ${created === 1 ? 'slot' : 'slots'} added.${skipped ? ` ${skipped} skipped (duplicate or past).` : ''}`,
      adding: 'Adding…',
      submit: 'Add slots',
    },
  },

  articles: {
    title: 'Insights articles',
    description: 'Published articles appear on the Insights page.',
    newArticle: 'New article',
    allArticles: 'All articles',
    publishedFilter: 'Published',
    draftsFilter: 'Drafts',
    empty: 'No articles yet.',
    columns: {
      title: 'Title',
      topic: 'Topic',
      status: 'Status',
      updated: 'Updated',
    },
  },

  articleEditor: {
    newTitle: 'New article',
    editTitle: 'Edit article',
    lastSaved: (dateLabel) => `Saved ${dateLabel}`,
    title: 'Title',
    titlePlaceholder: 'Received a legal notice? What to do next',
    slug: 'URL slug',
    slugPlaceholder: 'Made from the title if empty',
    slugHint: 'Lowercase words joined by hyphens.',
    topic: 'Topic',
    topicPlaceholder: 'Choose a topic',
    status: 'Status',
    summary: 'Summary',
    summaryPlaceholder: 'One or two sentences for the list.',
    body: 'Body (Markdown)',
    bodyHint: 'Use ## headings, - lists and **bold**. HTML isn’t shown.',
    preview: 'Preview',
    previewEmpty: 'Preview appears as you type.',
    savedPublished: 'Saved and published.',
    savedDraft: 'Draft saved.',
    create: 'Create article',
    save: 'Save article',
    back: 'Back to articles',
    viewOnSite: 'View on site',
    delete: 'Delete article',
    confirmLabel: 'Confirm delete',
    confirmBody: 'Delete this article permanently?',
    confirmYes: 'Delete',
    confirmNo: 'Keep',
  },

  users: {
    title: 'Users',
    description: 'People who have signed in. Admins are set with ADMIN_EMAILS.',
    role: 'Role',
    allRoles: 'All roles',
    clients: 'Clients',
    admins: 'Admins',
    searchPlaceholder: 'Name, email or phone',
    searchHint: 'Start of email, last phone digits, or whole name words.',
    empty: 'No users match.',
    columns: {
      name: 'Name',
      email: 'Email',
      phone: 'Phone',
      role: 'Role',
      joined: 'Joined',
      lastSignIn: 'Last sign-in',
    },
    never: 'Never',
  },

  whatsappContacts: {
    title: 'WhatsApp assistant',
    description: 'People who have messaged the assistant.',
    planDescription: (freeMessages, priceLabel, packMessages) =>
      `People who have messaged the assistant. ${freeMessages} free questions, then ${priceLabel} for ${packMessages}.`,
    searchPlaceholder: 'Phone or name',
    searchHint: 'Last phone digits or start of profile name.',
    emptySearch: 'No contacts match.',
    empty: 'No one has messaged yet.',
    columns: {
      number: 'WhatsApp number',
      name: 'Name',
      freeLeft: 'Free left',
      paidLeft: 'Paid left',
      status: 'Status',
      lastMessage: 'Last message',
    },
    notShared: 'Not shared',
    optedOut: 'Opted out',
    active: 'Active',
    payments: {
      title: 'Recent question pack payments',
      empty: 'No payment links sent yet.',
      columns: {
        contact: 'Contact',
        amount: 'Amount',
        questions: 'Questions',
        status: 'Status',
        created: 'Created',
        paid: 'Paid',
      },
      deletedContact: 'Deleted contact',
    },
  },

  whatsappContact: {
    back: 'All WhatsApp contacts',
    freeLeft: 'Free questions left',
    paidLeft: 'Paid questions left',
    status: 'Status',
    optedOutOn: (dateLabel) => `Opted out ${dateLabel}`,
    active: 'Active',
    noticeSent: 'Privacy notice sent',
    notYet: 'Not yet',
    closestService: 'Closest service',
    latestHandoff: 'Latest handoff',
    conversation: 'Conversation, newest first',
    noMessages: 'No messages yet.',
    fromContact: 'From contact',
    toContact: 'To contact',
    mediaMessage: (messageType) => `(${messageType} message)`,
    payments: 'Payments',
    noPayments: 'No payment links sent.',
    paymentColumns: {
      amount: 'Amount',
      questions: 'Questions',
      status: 'Status',
      sent: 'Sent',
      paid: 'Paid',
      razorpay: 'Razorpay payment',
    },
    grant: {
      title: 'Add questions',
      body: 'For goodwill or support. Counts as paid questions.',
      count: 'Number of questions',
      reason: 'Reason',
      added: (paidLeft) => `Questions added. Paid left: ${paidLeft}.`,
      adding: 'Adding…',
      submit: 'Add questions',
    },
    grantsTitle: 'Added by admins',
    grantsEmpty: 'None yet.',
    grantSummary: (count, reason) => `+${count}, ${reason}`,
    grantMeta: (adminLabel, dateLabel) => `${adminLabel}, ${dateLabel}`,
    grantedByFallback: 'Admin',
  },

  setupNotice: {
    title: 'Setup incomplete',
    whatsApp:
      'The assistant isn’t replying yet. Set WHATSAPP_TOKEN, WHATSAPP_PHONE_NUMBER_ID, WHATSAPP_APP_SECRET and WHATSAPP_VERIFY_TOKEN on the API, then register the webhook in Meta.',
    payments:
      'Question packs can’t be bought yet. Set RAZORPAY_KEY_ID, RAZORPAY_KEY_SECRET and RAZORPAY_WEBHOOK_SECRET, then add the webhook in Razorpay.',
  },
};
