// Admin screens for products, coupons, orders, document reviews and callbacks
export const adminCommerce = {
  nav: {
    products: 'Products',
    coupons: 'Coupons',
    orders: 'Orders',
    documentReviews: 'Doc reviews',
    callbacks: 'Callbacks',
  },
  pageTitles: {
    products: 'Products',
    newProduct: 'New product',
    editProduct: 'Edit product',
    coupons: 'Coupons',
    newCoupon: 'New coupon',
    editCoupon: 'Edit coupon',
    orders: 'Orders',
    order: 'Order',
    documentReviews: 'Document reviews',
    documentReview: 'Document review',
    callbacks: 'Callbacks',
  },

  overview: {
    ordersPaidToday: 'Orders paid today',
    revenuePaidToday: 'Collected today',
    openCallbacks: 'Open callbacks',
    documentReviewsToday: 'Reviews today',
  },

  callbackStatuses: {
    new: 'New',
    called: 'Called',
    'no-answer': 'No answer',
    closed: 'Closed',
  },

  products: {
    title: 'Products',
    description: 'Fixed-price services in the catalogue.',
    newProduct: 'New product',
    category: 'Category',
    allCategories: 'All categories',
    visibility: 'Visibility',
    all: 'All',
    published: 'Published',
    hidden: 'Hidden',
    empty: 'No products yet.',
    columns: {
      title: 'Title',
      category: 'Category',
      price: 'Price',
      sort: 'Sort',
      visibility: 'Visibility',
      updated: 'Updated',
    },
    publish: 'Publish',
    unpublish: 'Unpublish',
  },

  productEditor: {
    title: 'Title',
    slug: 'URL slug',
    slugHint: 'Made from the title if empty.',
    category: 'Category',
    serviceCategory: 'Filed under',
    price: 'Price (₹)',
    compareAt: 'Was price (₹)',
    compareAtHint: 'Optional. Struck through when higher than the price.',
    summary: 'Summary',
    inclusions: 'What’s included',
    documents: 'Documents needed',
    listHint: 'One per line.',
    turnaround: 'Turnaround',
    turnaroundPlaceholder: '3–5 working days',
    governmentFee: 'Government fee note',
    sortOrder: 'Sort order',
    isPublished: 'Published on the site',
    faqTitle: 'FAQ',
    question: 'Question',
    answer: 'Answer',
    addQuestion: 'Add question',
    removeQuestion: 'Remove',
    invalidPrice: 'Enter a valid rupee amount.',
    saved: 'Product saved.',
    create: 'Create product',
    save: 'Save product',
    back: 'Back to products',
    viewOnSite: 'View on site',
    delete: 'Delete product',
    confirmBody: 'Delete this product permanently?',
    confirmYes: 'Delete',
    confirmNo: 'Keep',
    deleteBlocked: 'This product has orders. Unpublish it instead.',
  },

  coupons: {
    title: 'Coupons',
    description: 'Discount codes for checkout.',
    newCoupon: 'New coupon',
    empty: 'No coupons yet.',
    columns: {
      code: 'Code',
      discount: 'Discount',
      usage: 'Used',
      window: 'Valid',
      status: 'Status',
    },
    active: 'Active',
    inactive: 'Inactive',
    percentValue: (value) => `${value}% off`,
    flatValue: (amountLabel) => `${amountLabel} off`,
    usage: (count, maxRedemptions) => (maxRedemptions ? `${count} of ${maxRedemptions}` : `${count}`),
    always: 'Always',
    from: (dateLabel) => `From ${dateLabel}`,
    until: (dateLabel) => `Until ${dateLabel}`,
    between: (startLabel, endLabel) => `${startLabel} – ${endLabel}`,
  },

  couponEditor: {
    code: 'Code',
    codeHint: 'Saved in capitals.',
    type: 'Type',
    value: 'Value',
    valueHintPercent: 'Percent, 1–100.',
    valueHintFlat: 'Rupees off.',
    description: 'Description',
    maxDiscount: 'Max discount (₹)',
    maxDiscountHint: '0 means no cap.',
    minOrder: 'Minimum order (₹)',
    startsAt: 'Starts',
    endsAt: 'Ends',
    maxRedemptions: 'Total uses',
    perUserLimit: 'Uses per customer',
    unlimitedHint: '0 means unlimited.',
    categories: 'Applies to',
    categoriesHint: 'None selected means all.',
    isActive: 'Active',
    invalidValue: 'Enter a valid value.',
    saved: 'Coupon saved.',
    create: 'Create coupon',
    save: 'Save coupon',
    back: 'Back to coupons',
    delete: 'Delete coupon',
    confirmBody: 'Delete this coupon?',
    confirmYes: 'Delete',
    confirmNo: 'Keep',
    deleteBlocked: 'This coupon has been used. Deactivate it instead.',
    redemptions: (count) => `Used ${count} times`,
  },

  orders: {
    title: 'Orders',
    description: 'Catalogue orders and payments.',
    searchPlaceholder: 'LO- reference, email, phone or name',
    empty: 'No orders match.',
    count: (total) => `${total} ${total === 1 ? 'order' : 'orders'}`,
    columns: {
      reference: 'Reference',
      client: 'Client',
      items: 'Items',
      total: 'Total',
      status: 'Status',
      created: 'Created',
    },
  },

  orderDetail: {
    breadcrumb: 'Orders',
    notFound: (referenceCode) => `No order found with reference ${referenceCode}.`,
    meta: (dateLabel) => `Placed ${dateLabel}`,
    clientTitle: 'Client',
    name: 'Name',
    email: 'Email',
    phone: 'Phone',
    language: 'Language',
    whatsApp: 'WhatsApp updates',
    optedIn: 'Opted in',
    notOptedIn: 'Not opted in',
    account: 'Account',
    linkedAccount: 'Linked to an account',
    guest: 'Guest checkout',
    notes: 'Client notes',
    itemsTitle: 'Items',
    subtotal: 'Subtotal',
    discountWithCode: (code) => `Discount (${code})`,
    total: 'Total',
    refunded: 'Refunded',
    paidAt: 'Paid',
    razorpayOrder: 'Razorpay order',
    razorpayPayment: 'Razorpay payment',
    requestTitle: 'Service request',
    noRequest: 'Created once paid.',
    historyTitle: 'History',
    refundsTitle: 'Refunds',
    noRefunds: 'No refunds.',
    refundSummary: (amountLabel, statusLabel) => `${amountLabel}, ${statusLabel}`,
    refundMeta: (adminLabel, dateLabel) => `${adminLabel}, ${dateLabel}`,
    refund: {
      title: 'Issue a refund',
      full: (amountLabel) => `Full remainder (${amountLabel})`,
      partial: 'Partial amount',
      amount: 'Amount (₹)',
      reason: 'Reason',
      reasonPlaceholder: 'Why is this refunded?',
      submit: 'Refund',
      busy: 'Refunding…',
      confirm: (amountLabel) => `Refund ${amountLabel}? This can’t be undone.`,
      confirmYes: 'Yes, refund',
      confirmNo: 'Cancel',
      done: 'Refund started.',
      invalidAmount: (maxLabel) => `Enter an amount up to ${maxLabel}.`,
      reasonRequired: 'Add a reason.',
      notRefundable: 'Only paid orders with money left can be refunded.',
    },
  },

  documentReviews: {
    title: 'Document reviews',
    description: 'AI reviews requested by clients.',
    empty: 'No reviews match.',
    columns: {
      reference: 'Reference',
      owner: 'Client',
      file: 'File',
      status: 'Status',
      risk: 'Risk',
      created: 'Uploaded',
    },
  },

  documentReviewDetail: {
    breadcrumb: 'Document reviews',
    meta: (dateLabel) => `Uploaded ${dateLabel}`,
    owner: 'Client',
    file: 'File',
    pages: 'Pages (estimate)',
    attempts: 'Attempts',
    tokens: 'Tokens',
    tokensValue: (inputTokens, outputTokens) => `${inputTokens} in, ${outputTokens} out`,
    lastError: 'Last error',
    request: 'Lawyer review',
    none: 'None',
    fileDeleted: 'File deleted',
    reportTitle: 'Report',
    noReport: 'No report yet.',
  },

  callbacks: {
    title: 'Callbacks',
    description: 'People who asked for a call.',
    searchPlaceholder: 'LK- reference or phone',
    empty: 'No callbacks match.',
    columns: {
      reference: 'Reference',
      name: 'Name',
      phone: 'Phone',
      when: 'Best time',
      language: 'Language',
      status: 'Status',
    },
    requested: (dateLabel) => `Requested ${dateLabel}`,
    topic: 'Topic',
    service: 'Service',
    note: 'Note',
    notePlaceholder: 'What happened on the call?',
    save: 'Save',
    saved: 'Saved.',
    nothingChanged: 'Change the status or add a note.',
    historyTitle: 'History',
    noteMeta: (adminLabel, dateLabel) => `${adminLabel}, ${dateLabel}`,
    adminFallback: 'Admin',
  },
};
