// "Call me back" requests (flag callbackRequests)
export const callback = {
  trigger: 'Call me back',
  title: 'Request a call back',
  body: 'Share your number. We’ll call you.',
  fullName: 'Full name',
  phone: 'Phone',
  phonePlaceholder: '+91',
  languageLabel: 'Language',
  timeLabel: 'Best time',
  timeWindows: {
    now: 'As soon as possible',
    morning: 'Morning (9 am–12 pm)',
    afternoon: 'Afternoon (12–4 pm)',
    evening: 'Evening (4–8 pm)',
  },
  topicLabel: 'Topic',
  topicPlaceholder: 'Optional, e.g. rent agreement',
  consentBefore: 'I agree to be called and to the ',
  consentLink: 'privacy policy',
  consentAfter: '.',
  consentRequired: 'Please accept to continue.',
  submit: 'Request call',
  busy: 'Sending…',
  close: 'Close',
  successTitle: 'Request received',
  success: (referenceCode) => `Reference ${referenceCode}. We’ll call you soon.`,
  duplicate: (referenceCode) => `You already have a pending request (${referenceCode}). We’ll call you soon.`,
  done: 'Done',
  contactNote: 'Prefer a call? We’ll ring you.',
};
