// Catalogue, product pages, checkout and client orders (flags serviceCatalog, onlinePayments, coupons)
export const commerce = {
  labels: {
    productCategories: {
      property: { label: 'Property', summary: 'Verification, deeds and rent agreements.' },
      business: { label: 'Business & startup', summary: 'Company setup, GST and trademarks.' },
      documents: { label: 'Documents & agreements', summary: 'Notices, agreements and affidavits.' },
      personal: { label: 'Personal & family', summary: 'Wills, consumer and family matters.' },
    },
    orderStatuses: {
      created: 'Awaiting payment',
      paid: 'Paid',
      failed: 'Payment failed',
      refunded: 'Refunded',
      'partially-refunded': 'Partly refunded',
      cancelled: 'Cancelled',
    },
    couponTypes: {
      percent: 'Percent off',
      flat: 'Flat amount off',
    },
    refundStatuses: {
      pending: 'Pending',
      processed: 'Processed',
      failed: 'Failed',
    },
    // Language names in the reader's language; the native name is added next to it
    languages: {
      en: 'English',
      hi: 'Hindi',
      bn: 'Bengali',
      ta: 'Tamil',
      te: 'Telugu',
      mr: 'Marathi',
      gu: 'Gujarati',
      kn: 'Kannada',
      ml: 'Malayalam',
      pa: 'Punjabi',
    },
  },

  catalogue: {
    metadata: {
      title: 'Legal services',
      description: 'Fixed-price legal services with clear timelines.',
    },
    header: {
      title: 'Legal services',
      lead: 'Fixed prices. Clear timelines.',
    },
    tabsLabel: 'Service categories',
    allCategories: 'All',
    empty: 'No services here yet.',
    buyNow: 'Buy now',
    getStarted: 'Get started',
    wasPrice: (priceLabel) => `Was ${priceLabel}`,
    otherHelp: {
      title: 'Need something else?',
      body: 'Pick an area and tell us more.',
    },
  },

  product: {
    breadcrumb: 'Services',
    turnaroundLabel: 'Turnaround',
    inclusionsTitle: 'What’s included',
    documentsTitle: 'Documents needed',
    faqTitle: 'Questions',
    governmentFeeLabel: 'Government fees',
    buyNow: 'Buy now',
    request: 'Request this',
    buyNote: 'Secure payment via Razorpay.',
    requestNote: 'We confirm the fee before starting.',
    stickyLabel: 'Buy this service',
    save: (amountLabel, percent) => `Save ${amountLabel} (${percent}% off)`,
    stepsTitle: "How it works",
    steps: [
      { title: "Pay the fixed fee", description: "Secure payment. Receipt by email." },
      { title: "Share your documents", description: "Upload now or later from your account." },
      { title: "We work on it", description: "Track progress in your account." },
      { title: "Delivered to you", description: "Download the result from your account." },
    ],
    assurances: ["Handled by our in-house legal team", "Your documents stay private", "Cancel before work starts"],
    questionsTitle: "Have a question first?",
    contactLink: "Talk to us",
    relatedTitle: "Related services",
  },

  checkout: {
    metadata: { title: 'Checkout' },
    title: 'Checkout',
    backToService: 'Back to service',
    summaryTitle: 'Order summary',
    subtotal: 'Subtotal',
    discount: 'Discount',
    total: 'Total',
    detailsTitle: 'Your details',
    fullName: 'Full name',
    email: 'Email',
    phone: 'Phone',
    phonePlaceholder: '+91',
    languageLabel: 'Preferred language',
    descriptionLabel: 'Anything we should know?',
    descriptionHint: 'Optional. Mention deadlines or key facts.',
    coupon: {
      label: 'Coupon code',
      apply: 'Apply',
      applying: 'Checking…',
      remove: 'Remove',
      applied: (code) => `${code} applied.`,
    },
    consentBefore: 'I agree to the ',
    consentLink: 'terms',
    consentAfter: ' and privacy policy.',
    consentRequired: 'Please accept to continue.',
    pay: (amountLabel) => `Pay ${amountLabel}`,
    placeOrder: 'Place order',
    processing: 'Processing…',
    secureNote: 'Payments are processed by Razorpay.',
    dismissed: 'Payment not completed. You can try again.',
    failed: 'Payment failed. Please try again.',
    verifyFailed: 'We couldn’t confirm the payment. If money was debited, contact us with your order reference.',
    notSetUp: 'Online payments aren’t available right now. Please contact us.',
    scriptFailed: 'Couldn’t open the payment window. Check your connection.',
    retry: 'Try again',
    orderReference: (referenceCode) => `Order ${referenceCode}`,
  },

  success: {
    metadata: { title: 'Order confirmed' },
    title: 'Order confirmed',
    referenceLabel: 'Order reference',
    requestLabel: 'Request reference',
    nextTitle: 'What happens next',
    nextSteps: ['Your receipt is on its way by email.', 'Our team reviews your details.', 'A professional contacts you to begin.'],
    viewOrder: 'View order',
    browse: 'Browse services',
  },

  orders: {
    metadataTitle: 'Orders',
    title: 'Orders',
    intro: 'Services you’ve bought.',
    empty: 'No orders yet.',
    emptyCta: 'Browse services',
    meta: (referenceCode, dateLabel) => `${referenceCode}, ${dateLabel}`,
    moreItems: (count) => `+${count} more`,
  },

  orderDetail: {
    metadataTitle: 'Order',
    breadcrumb: 'Orders',
    notFoundTitle: 'Order not found',
    notFoundBody: 'Sign in with the email used at checkout.',
    back: 'Back to orders',
    meta: (referenceCode, dateLabel) => `${referenceCode}, placed ${dateLabel}`,
    itemsTitle: 'Items',
    discountWithCode: (code) => `Discount (${code})`,
    refunded: 'Refunded',
    timelineTitle: 'Status',
    requestTitle: 'Your request',
    requestBody: (referenceCode) => `Our team is working on request ${referenceCode}.`,
    viewRequest: 'View request',
  },
};
