export const dashboard = {
  navLabel: 'My LexBridge',
  nav: {
    overview: 'Overview',
    requests: 'Requests',
    consultations: 'Consultations',
    documents: 'Documents',
    profile: 'Profile',
  },

  overview: {
    metadataTitle: 'Overview',
    welcome: (firstName) => (firstName ? `Welcome back, ${firstName}` : 'Welcome back'),
    intro: 'Your requests, consultations and documents.',
    activeRequests: 'Active requests',
    allRequests: 'All requests',
    noActiveBefore: 'No active requests.',
    noActiveFinder: 'Find the right help',
    noActiveOr: 'or',
    noActiveContact: 'send a request',
    requestMeta: (referenceCode, dateLabel) => `${referenceCode}, ${dateLabel}`,
    viewRequest: 'View',
    upcomingConsultation: 'Next consultation',
    noUpcoming: 'No upcoming consultations.',
    book: 'Book one',
    dateLabel: 'Date',
    timeLabel: 'Time',
    modeLabel: 'Mode',
    timeValue: (timeLabel) => `${timeLabel} IST`,
    joinVideo: 'Join video call',
    videoPending: 'Video link appears here before the call.',
    viewDetails: 'Details',
    documentsTitle: 'Documents',
    documentsCount: (count) => `${count} ${count === 1 ? 'document' : 'documents'}`,
    documentsDefault: 'Your shared documents.',
    documentsUnavailable: 'Documents unavailable right now.',
    documentCentre: 'Open documents',
    paymentsTitle: 'Payments',
    paymentsBody: 'Online payments coming soon.',
    supportTitle: 'Support',
    supportBody: 'Need help with a request?',
    supportCta: 'Contact us',
  },

  requests: {
    metadataTitle: 'Requests',
    title: 'Your requests',
    intro: 'All requests sent with this email.',
    emptyBefore: 'No requests yet.',
    emptyCta: 'Send one',
  },

  requestDetail: {
    metadataTitle: 'Request',
    notFoundTitle: 'Request not found',
    notFoundBody: 'Check the reference, or sign in with the email you used.',
    backToRequests: 'Back to requests',
    breadcrumb: 'Requests',
    meta: (referenceCode, dateLabel) => `${referenceCode}, submitted ${dateLabel}`,
    updates: 'Updates',
    description: 'What you told us',
    documents: 'Documents',
    noDocuments: 'No documents for this request.',
    shareTitle: 'Share a document',
  },

  consultations: {
    metadataTitle: 'Consultations',
    title: 'Consultations',
    book: 'Book',
    upcoming: 'Upcoming',
    noUpcoming: 'No upcoming consultations.',
    past: 'Past and cancelled',
    when: (dayLabel, timeLabel, minutes, modeLabel) => `${dayLabel}, ${timeLabel} IST, ${minutes} min, ${modeLabel}`,
    reference: (referenceCode) => `Ref ${referenceCode}`,
    joinVideo: 'Join video call',
    videoPending: 'Video link appears here before the call.',
    phoneNote: 'We’ll call you at the scheduled time.',
    cancel: 'Cancel',
    confirmLabel: 'Confirm cancellation',
    confirmBody: 'Cancel this consultation?',
    confirmYes: 'Yes, cancel',
    confirmBusy: 'Cancelling…',
    confirmNo: 'Keep it',
    tooLateBefore: (hours) => `Less than ${hours} hours left. To change it, `,
    tooLateLink: 'contact us',
    tooLateAfter: '.',
  },

  documents: {
    metadataTitle: 'Documents',
    title: 'Documents',
    intro: 'Private to you and the team on your matter.',
    yourDocuments: 'Your documents',
    empty: 'No documents yet.',
    referenceOption: (referenceCode, label) => `${referenceCode}: ${label}`,
  },

  profile: {
    metadataTitle: 'Profile',
    title: 'Profile',
    intro: 'Helps our team reach you.',
    fullName: 'Full name',
    phone: 'Phone',
    phonePlaceholder: '+91',
    emailLabel: 'Email',
    emailNote: 'Used to sign in, so it can’t be changed here.',
    saved: 'Profile saved.',
    save: 'Save',
    saving: 'Saving…',
  },
};
