export const forms = {
  serviceRequest: {
    fullName: 'Full name',
    email: 'Email',
    phone: 'Phone',
    phonePlaceholder: '+91',
    service: 'Service',
    servicePlaceholder: 'Choose a service',
    subtypePlaceholder: 'Choose one',
    descriptionLabel: 'Your requirement',
    descriptionPlaceholder: 'Tell us briefly…',
    descriptionHint: 'Mention any deadline or hearing date.',
    consentBefore: 'I agree to the ',
    consentLink: 'privacy policy',
    consentAfter: '. LexBridge is not a law firm.',
    submit: 'Send request',
    submitting: 'Sending…',
    stepsLabel: "Progress",
    stepMatter: "Your matter",
    stepDetails: "Your details",
    stepStatus: (current, total, name) => `Step ${current} of ${total}: ${name}`,
    continue: "Continue",
    back: "Back",
    stepErrors: {
      service: "Choose a service.",
      description: "Add a little more detail (at least 20 characters).",
    },
    successTitle: 'Request received',
    successReferenceBefore: 'Reference: ',
    successReferenceAfter: '. A confirmation is on its way to your email.',
    successNextBefore: 'Track it in ',
    successNextLink: 'My LexBridge',
    successNextAfter: ' with the same email.',
    successNextNoAccounts: 'Our team will contact you soon.',
  },

  upload: {
    title: 'Upload a document',
    submit: 'Upload',
    busy: 'Uploading…',
    relatedRequest: 'Related request',
    notLinked: 'Not linked',
    fileLabel: 'File',
    fileHint: (maxSizeLabel) => `PDF, JPG, PNG or DOCX, up to ${maxSizeLabel}.`,
    chooseFile: 'Choose a file.',
    wrongType: 'Use a PDF, JPG, PNG or DOCX file.',
    tooLarge: (maxSizeLabel) => `Files can be up to ${maxSizeLabel}.`,
    chooseRequest: 'Choose the related request.',
    uploaded: (fileName) => `${fileName} uploaded.`,
  },

  documentList: {
    empty: 'No documents yet.',
    typeLabels: {
      'application/pdf': 'PDF',
      'image/jpeg': 'JPG',
      'image/png': 'PNG',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document': 'Word',
    },
    fallbackType: 'File',
    uploadedOn: (dateLabel) => `uploaded ${dateLabel}`,
    sharedByTeam: 'shared by LexBridge',
    forReference: (referenceCode) => `for ${referenceCode}`,
    download: 'Download',
  },

  timeline: {
    empty: 'No updates yet.',
  },

  // Shown instead of the API's English validation text for fields we know
  fieldErrors: {
    FullName: 'Enter your full name.',
    Email: 'Enter a valid email.',
    Phone: 'Enter a valid phone number.',
    ServiceCategory: 'Choose a service.',
    Description: 'Please add a little more detail.',
    ConsentGiven: 'Please accept to continue.',
    Code: 'Enter the 6-digit code.',
    Messages: 'Enter a number from 1 to 500.',
    Reason: 'Add a reason.',
    Title: 'Add a title.',
    Topic: 'Choose a topic.',
    Summary: 'Keep the summary short.',
    Slug: 'Use lowercase words joined by hyphens.',
    Body: 'Add the article text.',
  },
  checkFields: 'Please check the highlighted fields.',
};
