// Labels for the intake catalog (packages/shared/src/intakeCatalog.js): subtype names, the
// conditional questions each subtype asks, and every option value. Keys must mirror the catalog.
export const intake = {
  detailsTitle: 'Matter details',
  subtypeLabel: 'What kind of matter is it?',
  otherLabel: 'Something else',
  choose: 'Choose…',
  fieldRequired: 'Please answer this question.',
  topicTitle: 'What is the consultation about?',
  topicIntro: 'A couple of quick questions so we put you in front of the right lawyer.',
  categoryLabel: 'Area of law',
  categoryPlaceholder: 'Choose an area…',

  subtypes: {
    'property-dispute': { label: 'Property dispute' },
    'landlord-tenant': { label: 'Landlord–tenant' },
    'title-verification': { label: 'Title verification' },
    'defective-product': { label: 'Defective product' },
    'deficient-service': { label: 'Deficient service' },
    'refund-dispute': { label: 'Refund dispute' },
    'cheque-bounce': { label: 'Cheque bounce' },
    'fir-bail': { label: 'FIR / bail' },
    'cyber-crime': { label: 'Cyber crime' },
    'employment-contract': { label: 'Employment contract' },
    'vendor-contract': { label: 'Vendor contract' },
    nda: { label: 'NDA' },
    'rental-agreement': { label: 'Rental agreement' },
    'company-incorporation': { label: 'Company incorporation' },
    'compliance-notice': { label: 'Compliance notice' },
    'legal-notice': { label: 'Legal notice' },
    agreement: { label: 'Agreement' },
    affidavit: { label: 'Affidavit' },
    application: { label: 'Application' },
    complaint: { label: 'Complaint' },
    'other-document': { label: 'Other document' },
    'document-review': { label: 'Document review' },
    'general-advice': { label: 'General advice' },
    'case-opinion': { label: 'Case opinion' },
    'document-consultation': { label: 'Document consultation' },
    other: { label: 'Something else' },
  },

  fields: {
    propertyType: { label: 'Property type' },
    disputeNature: { label: 'What is the dispute about?' },
    propertyCity: { label: 'City where the property is' },
    opposingPartyKnown: { label: 'Do you know the other party?' },
    amountAtStake: { label: 'Amount at stake' },
    yourRole: { label: 'Are you the landlord or the tenant?' },
    issue: { label: 'What is the issue?' },
    agreementExists: { label: 'Is there a written agreement?' },
    purpose: { label: 'What is this for?' },
    productType: { label: 'What product?' },
    vendorName: { label: 'Seller or brand name' },
    complaintFiledBefore: { label: 'Have you complained before?' },
    serviceType: { label: 'Which service?' },
    providerName: { label: 'Service provider name' },
    whatRefund: { label: 'What is the refund for?' },
    sellerType: { label: 'Where did you buy it?' },
    chequeAmount: { label: 'Cheque amount' },
    chequeDate: { label: 'Date on the cheque' },
    bankName: { label: 'Bank name' },
    noticeSent: { label: 'Was a legal notice sent?' },
    daysSinceDishonour: { label: 'How long ago was it dishonoured?' },
    firRegistered: { label: 'Is an FIR registered?' },
    policeStation: { label: 'Police station' },
    offenceType: { label: 'What allegation or offence?' },
    custodyStatus: { label: 'Custody status' },
    fraudType: { label: 'Type of fraud' },
    amountLost: { label: 'Amount lost' },
    platform: { label: 'App, website or platform' },
    roleLevel: { label: 'Seniority of the role' },
    contractStage: { label: 'Where are you in the contract?' },
    employerType: { label: 'Employer type' },
    valueRange: { label: 'Contract value' },
    entityType: { label: 'Type of entity' },
    foundersCount: { label: 'Number of founders' },
    authority: { label: 'Which authority?' },
    noticeType: { label: 'What does the notice say?' },
    responseDeadline: { label: 'Reply deadline' },
    noticeAgainst: { label: 'Notice against whom?' },
    noticeMatter: { label: 'What is the notice about?' },
    agreementType: { label: 'What agreement?' },
    partiesCount: { label: 'How many parties?' },
    language: { label: 'Language' },
    affidavitPurpose: { label: 'What is the affidavit for?' },
    applicationTo: { label: 'Application to whom?' },
    applicationMatter: { label: 'What is the application about?' },
    complaintAgainst: { label: 'Complaint against whom?' },
    forum: { label: 'Where will it be filed?' },
    documentDescription: { label: 'Describe the document' },
    documentType: { label: 'Document type' },
    matterArea: { label: 'Area of law' },
    urgency: { label: 'How soon do you need it?' },
    deadline: { label: 'Deadline (if any)' },
    topicArea: { label: 'What area is the case in?' },
    caseStage: { label: 'Stage of the case' },
    documentCount: { label: 'How many documents?' },
  },

  options: {
    residential: 'Residential',
    commercial: 'Commercial',
    agricultural: 'Agricultural',
    plot: 'Plot / land',
    'title-ownership': 'Title or ownership',
    partition: 'Partition between co-owners',
    encroachment: 'Encroachment',
    possession: 'Possession',
    'builder-delay': 'Builder delay',
    yes: 'Yes',
    no: 'No',
    'under-1-lakh': 'Under ₹1 lakh',
    '1-10-lakh': '₹1–10 lakh',
    '10-lakh-1-crore': '₹10 lakh – ₹1 crore',
    'above-1-crore': 'Above ₹1 crore',
    'under-10k': 'Under ₹10,000',
    '10k-1-lakh': '₹10,000 – ₹1 lakh',
    'above-10-lakh': 'Above ₹10 lakh',
    landlord: 'Landlord',
    tenant: 'Tenant',
    'rent-default': 'Rent not being paid',
    eviction: 'Eviction',
    'deposit-refund': 'Security deposit refund',
    'repair-dispute': 'Repairs / maintenance',
    buying: 'Buying',
    selling: 'Selling',
    loan: 'Taking a loan',
    inheritance: 'Inheritance',
    builder: 'Builder / real estate',
    insurance: 'Insurance',
    banking: 'Banking',
    transport: 'Transport / courier',
    telecom: 'Telecom / internet',
    online: 'Online',
    offline: 'A physical store',
    both: 'Both online and offline',
    'under-30': 'Under 30 days',
    '30-90': '30–90 days',
    'over-90': 'More than 90 days',
    'not-arrested': 'No one arrested',
    'in-custody': 'Someone is in custody',
    released: 'Released on bail',
    'online-payment-fraud': 'Online payment fraud',
    'job-scam': 'Fake job offer',
    'investment-scam': 'Investment scam',
    'identity-theft': 'Identity theft',
    junior: 'Entry level',
    mid: 'Mid level',
    senior: 'Senior',
    leadership: 'Leadership',
    'offer-received': 'Offer received, not signed',
    signed: 'Already signed',
    'working-under-it': 'Currently working under it',
    startup: 'Startup',
    company: 'Established company',
    government: 'Government / PSU',
    foreign: 'Foreign employer',
    drafting: 'Still being drafted',
    'received-for-review': 'Received, needs review',
    hiring: 'For a hire or employee',
    vendor: 'For a vendor or supplier',
    investor: 'For an investor',
    partnership: 'Partnership',
    1: '1',
    2: '2',
    '3-plus': '3 or more',
    '2-5': '2–5',
    'more-than-5': 'More than 5',
    'pvt-ltd': 'Private limited',
    llp: 'LLP',
    opc: 'One person company',
    gst: 'GST',
    'income-tax': 'Income tax',
    roc: 'Registrar of Companies',
    labour: 'Labour department',
    'payment-due': 'Payment due',
    property: 'Property',
    consumer: 'Consumer issue',
    employment: 'Employment',
    english: 'English',
    hindi: 'Hindi',
    bilingual: 'Bilingual (English + Hindi)',
    'consumer-commission': 'Consumer commission',
    police: 'Police',
    court: 'Court',
    notice: 'Notice',
    'court-papers': 'Court papers',
    agreement: 'Agreement',
    'employment-contract': 'Employment contract',
    'rental-agreement': 'Rental agreement',
    family: 'Family',
    business: 'Business',
    criminal: 'Criminal',
    normal: 'No rush',
    'this-week': 'Within a week',
    urgent: 'Urgent',
    'notice-received': 'Notice received',
    'case-filed': 'Case filed',
    'hearing-ongoing': 'Hearings ongoing',
    appeal: 'Appeal',
    other: 'Other',
  },
};
