export const admin = {
  metadataTitle: 'एडमिन',
  navLabel: 'एडमिन',
  nav: {
    overview: 'सारांश',
    requests: 'अनुरोध',
    consultations: 'सलाह',
    slots: 'स्लॉट',
    articles: 'लेख',
    whatsapp: 'WhatsApp',
    users: 'यूज़र',
  },
  pageTitles: {
    overview: 'सारांश',
    requests: 'अनुरोध',
    request: 'अनुरोध',
    consultations: 'सलाह',
    slots: 'स्लॉट',
    articles: 'लेख',
    newArticle: 'नया लेख',
    editArticle: 'लेख बदलें',
    whatsapp: 'WhatsApp असिस्टेंट',
    whatsappContact: 'WhatsApp बातचीत',
    users: 'यूज़र',
  },

  accessNotice: {
    title: 'एडमिन अनुमति ज़रूरी',
    body: 'यह खाता एडमिन नहीं है। एडमिन ईमेल से साइन इन करें।',
    cta: 'My LexBridge पर जाएँ',
  },

  common: {
    status: 'स्थिति',
    allStatuses: 'सभी स्थितियाँ',
    search: 'खोजें',
    apply: 'लागू करें',
    saving: 'सेव हो रहा है…',
    notProvided: 'नहीं दिया',
    none: 'कोई नहीं',
  },

  overview: {
    title: 'सारांश',
    description: 'आज किन चीज़ों पर ध्यान देना है।',
    openRequests: 'खुले अनुरोध',
    upcomingConsultations: 'आने वाली सलाह',
    openSlots: 'खाली स्लॉट',
    publishedArticles: 'प्रकाशित लेख',
    requestsByStatus: 'स्थिति के अनुसार अनुरोध',
  },

  requests: {
    title: 'सेवा अनुरोध',
    description: 'वेबसाइट से आए सभी अनुरोध।',
    service: 'सेवा',
    allServices: 'सभी सेवाएँ',
    searchPlaceholder: 'रेफ़रेंस, नाम, ईमेल या फ़ोन',
    searchHint: 'रेफ़रेंस या ईमेल की शुरुआत, फ़ोन के आखिरी अंक या नाम के पूरे शब्द।',
    empty: 'इन फ़िल्टर से कोई अनुरोध नहीं मिला।',
    count: (total) => `${total} अनुरोध`,
    updating: ', अपडेट हो रहा है…',
    columns: {
      reference: 'रेफ़रेंस',
      client: 'क्लाइंट',
      service: 'सेवा',
      status: 'स्थिति',
      assigned: 'ज़िम्मेदार',
      received: 'मिला',
    },
    unassigned: 'किसी को नहीं सौंपा',
  },

  requestDetail: {
    breadcrumb: 'अनुरोध',
    notFound: (referenceCode) => `${referenceCode} रेफ़रेंस वाला कोई अनुरोध नहीं मिला।`,
    back: 'अनुरोधों पर वापस',
    meta: (serviceLabel, receivedLabel, sourceLabel) => `${serviceLabel}। ${receivedLabel} को ${sourceLabel} से मिला।`,
    saved: 'अनुरोध अपडेट हो गया।',
    clientTitle: 'क्लाइंट',
    name: 'नाम',
    email: 'ईमेल',
    phone: 'फ़ोन',
    whatsApp: 'WhatsApp अपडेट',
    optedIn: 'चालू',
    notOptedIn: 'बंद',
    openChat: 'चैट खोलें',
    chatGreeting: (fullName, referenceCode) => `नमस्ते ${fullName}, हम LexBridge से आपके अनुरोध ${referenceCode} के बारे में बात कर रहे हैं।`,
    consent: 'सहमति दर्ज',
    no: 'नहीं',
    account: 'खाता',
    linkedAccount: 'खाते से जुड़ा',
    guest: 'बिना साइन इन के भेजा',
    requirement: 'ज़रूरत',
    history: 'इतिहास',
    documents: 'दस्तावेज़',
    noDocuments: 'अभी कोई दस्तावेज़ नहीं।',
    shareTitle: 'क्लाइंट को भेजें',
    shareSubmit: 'अपलोड करके भेजें',
    update: {
      title: 'अनुरोध अपडेट करें',
      note: 'क्लाइंट के लिए नोट',
      noteHint: 'My LexBridge में दिखेगा। अंदरूनी बदलाव के लिए खाली छोड़ें।',
      assignedTo: 'किसे सौंपा',
      nothingChanged: 'पहले स्थिति बदलें, नोट लिखें या किसी और को सौंपें।',
      save: 'अपडेट सेव करें',
    },
  },

  consultations: {
    title: 'सलाह',
    description: 'तारीख के क्रम में बुकिंग। अपडेट के लिए खोलें।',
    empty: 'कोई सलाह नहीं मिली।',
    when: (dayLabel, timeLabel) => `${dayLabel}, ${timeLabel} IST`,
    summary: (clientLabel, typeLabel, modeLabel, referenceCode) => `${clientLabel}, ${typeLabel}, ${modeLabel}, ${referenceCode}`,
    clientFallback: 'क्लाइंट',
    email: 'ईमेल',
    notAvailable: 'उपलब्ध नहीं',
    phone: 'बुकिंग का फ़ोन',
    booked: 'बुक किया',
    duration: 'अवधि',
    minutes: (minutes) => `${minutes} मिनट`,
    whatsApp: 'WhatsApp अपडेट',
    optedIn: 'चालू',
    notOptedIn: 'बंद',
    editor: {
      statusHint: 'कैंसिल करने पर स्लॉट खाली हो जाता है।',
      meetingLink: 'मीटिंग लिंक',
      videoOnly: '(सिर्फ़ वीडियो)',
      meetingPlaceholder: 'https://meet.google.com/…',
      meetingHint: 'क्लाइंट को दिखेगा।',
      note: 'अंदरूनी नोट',
      nothingChanged: 'कुछ नहीं बदला।',
      saved: 'सलाह अपडेट हो गई।',
      save: 'बदलाव सेव करें',
    },
  },

  slots: {
    title: 'सलाह के स्लॉट',
    description: 'जिन समयों पर क्लाइंट बुक कर सकते हैं। सब IST में।',
    listLabel: 'तय स्लॉट',
    empty: 'अभी कोई स्लॉट नहीं। कुछ जोड़ें ताकि क्लाइंट बुक कर सकें।',
    durationShort: (minutes) => `${minutes} मिनट`,
    delete: 'हटाएँ',
    deleting: 'हटा रहे हैं…',
    deleteLabel: (timeLabel, dayLabel) => `${dayLabel} का ${timeLabel} स्लॉट हटाएँ`,
    create: {
      title: 'नए स्लॉट खोलें',
      date: 'तारीख',
      times: 'शुरू होने का समय (IST, 24 घंटे)',
      timesPlaceholder: '10:00, 11:00, 15:30',
      timesHint: 'कॉमा या स्पेस से अलग करें।',
      duration: 'अवधि',
      minutes: (minutes) => `${minutes} मिनट`,
      chooseDate: 'तारीख चुनें।',
      invalidTimes: (times) => `10:00 जैसा 24 घंटे वाला समय लिखें। जाँचें: ${times}।`,
      addTime: 'कम से कम एक समय जोड़ें।',
      added: (created, skipped) => `${created} स्लॉट जोड़े गए।${skipped ? ` ${skipped} छोड़े गए (दोहराए या बीते हुए)।` : ''}`,
      adding: 'जोड़ रहे हैं…',
      submit: 'स्लॉट जोड़ें',
    },
  },

  articles: {
    title: 'जानकारी वाले लेख',
    description: 'प्रकाशित लेख जानकारी पेज पर दिखते हैं।',
    newArticle: 'नया लेख',
    allArticles: 'सभी लेख',
    publishedFilter: 'प्रकाशित',
    draftsFilter: 'ड्राफ़्ट',
    empty: 'अभी कोई लेख नहीं।',
    columns: {
      title: 'शीर्षक',
      topic: 'विषय',
      status: 'स्थिति',
      updated: 'अपडेट',
    },
  },

  articleEditor: {
    newTitle: 'नया लेख',
    editTitle: 'लेख बदलें',
    lastSaved: (dateLabel) => `${dateLabel} को सेव`,
    title: 'शीर्षक',
    titlePlaceholder: 'लीगल नोटिस मिला? अब क्या करें',
    slug: 'URL स्लग',
    slugPlaceholder: 'खाली छोड़ने पर शीर्षक से बनेगा',
    slugHint: 'छोटे अक्षरों वाले शब्द, बीच में हाइफ़न।',
    topic: 'विषय',
    topicPlaceholder: 'विषय चुनें',
    status: 'स्थिति',
    summary: 'सारांश',
    summaryPlaceholder: 'लिस्ट के लिए एक-दो वाक्य।',
    body: 'लेख (Markdown)',
    bodyHint: '## से हेडिंग, - से लिस्ट और **बोल्ड** लिखें। HTML नहीं दिखेगा।',
    preview: 'प्रीव्यू',
    previewEmpty: 'लिखते ही प्रीव्यू दिखेगा।',
    savedPublished: 'सेव और प्रकाशित हो गया।',
    savedDraft: 'ड्राफ़्ट सेव हो गया।',
    create: 'लेख बनाएँ',
    save: 'लेख सेव करें',
    back: 'लेखों पर वापस',
    viewOnSite: 'साइट पर देखें',
    delete: 'लेख हटाएँ',
    confirmLabel: 'हटाने की पुष्टि',
    confirmBody: 'यह लेख हमेशा के लिए हटाएँ?',
    confirmYes: 'हटाएँ',
    confirmNo: 'रहने दें',
  },

  users: {
    title: 'यूज़र',
    description: 'जिन्होंने साइन इन किया है। एडमिन ADMIN_EMAILS से तय होते हैं।',
    role: 'भूमिका',
    allRoles: 'सभी भूमिकाएँ',
    clients: 'क्लाइंट',
    admins: 'एडमिन',
    searchPlaceholder: 'नाम, ईमेल या फ़ोन',
    searchHint: 'ईमेल की शुरुआत, फ़ोन के आखिरी अंक या नाम के पूरे शब्द।',
    empty: 'कोई यूज़र नहीं मिला।',
    columns: {
      name: 'नाम',
      email: 'ईमेल',
      phone: 'फ़ोन',
      role: 'भूमिका',
      joined: 'जुड़े',
      lastSignIn: 'आखिरी साइन इन',
    },
    never: 'कभी नहीं',
  },

  whatsappContacts: {
    title: 'WhatsApp असिस्टेंट',
    description: 'जिन्होंने असिस्टेंट को मैसेज किया है।',
    planDescription: (freeMessages, priceLabel, packMessages) =>
      `जिन्होंने असिस्टेंट को मैसेज किया है। ${freeMessages} सवाल मुफ़्त, फिर ${priceLabel} में ${packMessages}।`,
    searchPlaceholder: 'फ़ोन या नाम',
    searchHint: 'फ़ोन के आखिरी अंक या प्रोफ़ाइल नाम की शुरुआत।',
    emptySearch: 'कोई संपर्क नहीं मिला।',
    empty: 'अभी तक किसी ने मैसेज नहीं किया।',
    columns: {
      number: 'WhatsApp नंबर',
      name: 'नाम',
      freeLeft: 'मुफ़्त बाकी',
      paidLeft: 'पेड बाकी',
      status: 'स्थिति',
      lastMessage: 'आखिरी मैसेज',
    },
    notShared: 'नहीं बताया',
    optedOut: 'बंद किया',
    active: 'चालू',
    payments: {
      title: 'हाल के सवाल पैक पेमेंट',
      empty: 'अभी कोई पेमेंट लिंक नहीं भेजा।',
      columns: {
        contact: 'संपर्क',
        amount: 'रकम',
        questions: 'सवाल',
        status: 'स्थिति',
        created: 'बनाया',
        paid: 'पेमेंट',
      },
      deletedContact: 'हटाया गया संपर्क',
    },
  },

  whatsappContact: {
    back: 'सभी WhatsApp संपर्क',
    freeLeft: 'मुफ़्त सवाल बाकी',
    paidLeft: 'पेड सवाल बाकी',
    status: 'स्थिति',
    optedOutOn: (dateLabel) => `${dateLabel} को बंद किया`,
    active: 'चालू',
    noticeSent: 'प्राइवेसी सूचना भेजी',
    notYet: 'अभी नहीं',
    closestService: 'सबसे नज़दीकी सेवा',
    latestHandoff: 'आखिरी हैंडऑफ़',
    conversation: 'बातचीत, नई पहले',
    noMessages: 'अभी कोई मैसेज नहीं।',
    fromContact: 'संपर्क से',
    toContact: 'संपर्क को',
    mediaMessage: (messageType) => `(${messageType} मैसेज)`,
    payments: 'पेमेंट',
    noPayments: 'कोई पेमेंट लिंक नहीं भेजा।',
    paymentColumns: {
      amount: 'रकम',
      questions: 'सवाल',
      status: 'स्थिति',
      sent: 'भेजा',
      paid: 'पेमेंट',
      razorpay: 'Razorpay पेमेंट',
    },
    grant: {
      title: 'सवाल जोड़ें',
      body: 'सहायता या सद्भावना के लिए। ये पेड सवालों में गिने जाएँगे।',
      count: 'सवालों की संख्या',
      reason: 'कारण',
      added: (paidLeft) => `सवाल जुड़ गए। पेड बाकी: ${paidLeft}।`,
      adding: 'जोड़ रहे हैं…',
      submit: 'सवाल जोड़ें',
    },
    grantsTitle: 'एडमिन ने जोड़े',
    grantsEmpty: 'अभी कोई नहीं।',
    grantSummary: (count, reason) => `+${count}, ${reason}`,
    grantMeta: (adminLabel, dateLabel) => `${adminLabel}, ${dateLabel}`,
    grantedByFallback: 'एडमिन',
  },

  setupNotice: {
    title: 'सेटअप अधूरा है',
    whatsApp:
      'असिस्टेंट अभी जवाब नहीं दे रहा। API पर WHATSAPP_TOKEN, WHATSAPP_PHONE_NUMBER_ID, WHATSAPP_APP_SECRET और WHATSAPP_VERIFY_TOKEN सेट करें, फिर Meta में वेबहुक जोड़ें।',
    payments:
      'सवाल पैक अभी नहीं खरीदे जा सकते। RAZORPAY_KEY_ID, RAZORPAY_KEY_SECRET और RAZORPAY_WEBHOOK_SECRET सेट करें, फिर Razorpay में वेबहुक जोड़ें।',
  },
};
