// प्रोडक्ट, कूपन, ऑर्डर, दस्तावेज़ समीक्षा और कॉल बैक के एडमिन पेज
export const adminCommerce = {
  nav: {
    products: 'प्रोडक्ट',
    coupons: 'कूपन',
    orders: 'ऑर्डर',
    documentReviews: 'दस्तावेज़ समीक्षा',
    callbacks: 'कॉल बैक',
  },
  pageTitles: {
    products: 'प्रोडक्ट',
    newProduct: 'नया प्रोडक्ट',
    editProduct: 'प्रोडक्ट बदलें',
    coupons: 'कूपन',
    newCoupon: 'नया कूपन',
    editCoupon: 'कूपन बदलें',
    orders: 'ऑर्डर',
    order: 'ऑर्डर',
    documentReviews: 'दस्तावेज़ समीक्षा',
    documentReview: 'दस्तावेज़ समीक्षा',
    callbacks: 'कॉल बैक',
  },

  overview: {
    ordersPaidToday: 'आज भुगतान वाले ऑर्डर',
    revenuePaidToday: 'आज की वसूली',
    openCallbacks: 'बाकी कॉल बैक',
    documentReviewsToday: 'आज की समीक्षाएं',
  },

  callbackStatuses: {
    new: 'नया',
    called: 'कॉल हो गई',
    'no-answer': 'जवाब नहीं मिला',
    closed: 'बंद',
  },

  products: {
    title: 'प्रोडक्ट',
    description: 'कैटलॉग में तय कीमत वाली सेवाएं।',
    newProduct: 'नया प्रोडक्ट',
    category: 'श्रेणी',
    allCategories: 'सभी श्रेणियां',
    visibility: 'दिखना',
    all: 'सभी',
    published: 'प्रकाशित',
    hidden: 'छिपा हुआ',
    empty: 'अभी कोई प्रोडक्ट नहीं है।',
    columns: {
      title: 'शीर्षक',
      category: 'श्रेणी',
      price: 'कीमत',
      sort: 'क्रम',
      visibility: 'दिखना',
      updated: 'अपडेट',
    },
    publish: 'प्रकाशित करें',
    unpublish: 'छिपाएं',
  },

  productEditor: {
    title: 'शीर्षक',
    slug: 'URL स्लग',
    slugHint: 'खाली छोड़ने पर शीर्षक से बनेगा।',
    category: 'श्रेणी',
    serviceCategory: 'किस सेवा में दर्ज हो',
    price: 'कीमत (₹)',
    compareAt: 'पहले की कीमत (₹)',
    compareAtHint: 'ज़रूरी नहीं। कीमत से ज़्यादा होने पर कटी हुई दिखेगी।',
    summary: 'सार',
    inclusions: 'क्या शामिल है',
    documents: 'ज़रूरी दस्तावेज़',
    listHint: 'हर लाइन में एक।',
    turnaround: 'समय-सीमा',
    turnaroundPlaceholder: '3–5 कामकाजी दिन',
    governmentFee: 'सरकारी फीस की जानकारी',
    sortOrder: 'क्रम',
    isPublished: 'साइट पर प्रकाशित',
    faqTitle: 'FAQ',
    question: 'सवाल',
    answer: 'जवाब',
    addQuestion: 'सवाल जोड़ें',
    removeQuestion: 'हटाएं',
    invalidPrice: 'सही रकम रुपये में लिखें।',
    saved: 'प्रोडक्ट सेव हो गया।',
    create: 'प्रोडक्ट बनाएं',
    save: 'प्रोडक्ट सेव करें',
    back: 'प्रोडक्ट पर वापस',
    viewOnSite: 'साइट पर देखें',
    delete: 'प्रोडक्ट हटाएं',
    confirmBody: 'यह प्रोडक्ट हमेशा के लिए हटाएं?',
    confirmYes: 'हटाएं',
    confirmNo: 'रहने दें',
    deleteBlocked: 'इस प्रोडक्ट के ऑर्डर हैं। इसे छिपा दें।',
  },

  coupons: {
    title: 'कूपन',
    description: 'चेकआउट के छूट कोड।',
    newCoupon: 'नया कूपन',
    empty: 'अभी कोई कूपन नहीं है।',
    columns: {
      code: 'कोड',
      discount: 'छूट',
      usage: 'इस्तेमाल',
      window: 'मान्य',
      status: 'स्थिति',
    },
    active: 'चालू',
    inactive: 'बंद',
    percentValue: (value) => `${value}% छूट`,
    flatValue: (amountLabel) => `${amountLabel} छूट`,
    usage: (count, maxRedemptions) => (maxRedemptions ? `${maxRedemptions} में से ${count}` : `${count}`),
    always: 'हमेशा',
    from: (dateLabel) => `${dateLabel} से`,
    until: (dateLabel) => `${dateLabel} तक`,
    between: (startLabel, endLabel) => `${startLabel} – ${endLabel}`,
  },

  couponEditor: {
    code: 'कोड',
    codeHint: 'कैपिटल अक्षरों में सेव होगा।',
    type: 'प्रकार',
    value: 'मान',
    valueHintPercent: 'प्रतिशत, 1–100।',
    valueHintFlat: 'रुपये की छूट।',
    description: 'विवरण',
    maxDiscount: 'अधिकतम छूट (₹)',
    maxDiscountHint: '0 का मतलब कोई सीमा नहीं।',
    minOrder: 'न्यूनतम ऑर्डर (₹)',
    startsAt: 'शुरू',
    endsAt: 'खत्म',
    maxRedemptions: 'कुल इस्तेमाल',
    perUserLimit: 'हर ग्राहक के इस्तेमाल',
    unlimitedHint: '0 का मतलब असीमित।',
    categories: 'किन पर लागू',
    categoriesHint: 'कुछ न चुनें तो सभी पर।',
    isActive: 'चालू',
    invalidValue: 'सही मान लिखें।',
    saved: 'कूपन सेव हो गया।',
    create: 'कूपन बनाएं',
    save: 'कूपन सेव करें',
    back: 'कूपन पर वापस',
    delete: 'कूपन हटाएं',
    confirmBody: 'यह कूपन हटाएं?',
    confirmYes: 'हटाएं',
    confirmNo: 'रहने दें',
    deleteBlocked: 'यह कूपन इस्तेमाल हो चुका है। इसे बंद कर दें।',
    redemptions: (count) => `${count} बार इस्तेमाल`,
  },

  orders: {
    title: 'ऑर्डर',
    description: 'कैटलॉग के ऑर्डर और भुगतान।',
    searchPlaceholder: 'LO- नंबर, ईमेल, फ़ोन या नाम',
    empty: 'कोई ऑर्डर नहीं मिला।',
    count: (total) => `${total} ऑर्डर`,
    columns: {
      reference: 'नंबर',
      client: 'क्लाइंट',
      items: 'सेवाएं',
      total: 'कुल',
      status: 'स्थिति',
      created: 'बना',
    },
  },

  orderDetail: {
    breadcrumb: 'ऑर्डर',
    notFound: (referenceCode) => `${referenceCode} नंबर का कोई ऑर्डर नहीं मिला।`,
    meta: (dateLabel) => `${dateLabel} को किया गया`,
    clientTitle: 'क्लाइंट',
    name: 'नाम',
    email: 'ईमेल',
    phone: 'फ़ोन',
    language: 'भाषा',
    whatsApp: 'WhatsApp अपडेट',
    optedIn: 'चालू',
    notOptedIn: 'बंद',
    account: 'खाता',
    linkedAccount: 'खाते से जुड़ा',
    guest: 'बिना खाते के',
    notes: 'क्लाइंट की बातें',
    itemsTitle: 'सेवाएं',
    subtotal: 'कुल राशि',
    discountWithCode: (code) => `छूट (${code})`,
    total: 'देय राशि',
    refunded: 'रिफंड',
    paidAt: 'भुगतान',
    razorpayOrder: 'Razorpay ऑर्डर',
    razorpayPayment: 'Razorpay भुगतान',
    requestTitle: 'सेवा अनुरोध',
    noRequest: 'भुगतान के बाद बनेगा।',
    historyTitle: 'इतिहास',
    refundsTitle: 'रिफंड',
    noRefunds: 'कोई रिफंड नहीं।',
    refundSummary: (amountLabel, statusLabel) => `${amountLabel}, ${statusLabel}`,
    refundMeta: (adminLabel, dateLabel) => `${adminLabel}, ${dateLabel}`,
    refund: {
      title: 'रिफंड करें',
      full: (amountLabel) => `बाकी पूरी रकम (${amountLabel})`,
      partial: 'कुछ रकम',
      amount: 'रकम (₹)',
      reason: 'कारण',
      reasonPlaceholder: 'रिफंड क्यों किया जा रहा है?',
      submit: 'रिफंड करें',
      busy: 'रिफंड हो रहा है…',
      confirm: (amountLabel) => `${amountLabel} रिफंड करें? इसे वापस नहीं लिया जा सकता।`,
      confirmYes: 'हां, रिफंड करें',
      confirmNo: 'रद्द करें',
      done: 'रिफंड शुरू हो गया।',
      invalidAmount: (maxLabel) => `${maxLabel} तक की रकम लिखें।`,
      reasonRequired: 'कारण लिखें।',
      notRefundable: 'सिर्फ़ भुगतान वाले और बची रकम वाले ऑर्डर रिफंड हो सकते हैं।',
    },
  },

  documentReviews: {
    title: 'दस्तावेज़ समीक्षा',
    description: 'क्लाइंट की AI समीक्षाएं।',
    empty: 'कोई समीक्षा नहीं मिली।',
    columns: {
      reference: 'नंबर',
      owner: 'क्लाइंट',
      file: 'फ़ाइल',
      status: 'स्थिति',
      risk: 'जोखिम',
      created: 'अपलोड',
    },
  },

  documentReviewDetail: {
    breadcrumb: 'दस्तावेज़ समीक्षा',
    meta: (dateLabel) => `${dateLabel} को अपलोड`,
    owner: 'क्लाइंट',
    file: 'फ़ाइल',
    pages: 'पेज (अनुमान)',
    attempts: 'प्रयास',
    tokens: 'टोकन',
    tokensValue: (inputTokens, outputTokens) => `${inputTokens} इनपुट, ${outputTokens} आउटपुट`,
    lastError: 'आखिरी गड़बड़ी',
    request: 'वकील समीक्षा',
    none: 'कोई नहीं',
    fileDeleted: 'फ़ाइल हटाई गई',
    reportTitle: 'रिपोर्ट',
    noReport: 'अभी रिपोर्ट नहीं है।',
  },

  callbacks: {
    title: 'कॉल बैक',
    description: 'जिन्होंने कॉल मांगी है।',
    searchPlaceholder: 'LK- नंबर या फ़ोन',
    empty: 'कोई कॉल बैक नहीं मिला।',
    columns: {
      reference: 'नंबर',
      name: 'नाम',
      phone: 'फ़ोन',
      when: 'सही समय',
      language: 'भाषा',
      status: 'स्थिति',
    },
    requested: (dateLabel) => `${dateLabel} को अनुरोध`,
    topic: 'विषय',
    service: 'सेवा',
    note: 'नोट',
    notePlaceholder: 'कॉल पर क्या हुआ?',
    save: 'सेव करें',
    saved: 'सेव हो गया।',
    nothingChanged: 'स्थिति बदलें या नोट लिखें।',
    historyTitle: 'इतिहास',
    noteMeta: (adminLabel, dateLabel) => `${adminLabel}, ${dateLabel}`,
    adminFallback: 'एडमिन',
  },
};
