// "मुझे कॉल करें" अनुरोध
export const callback = {
  trigger: 'मुझे कॉल करें',
  title: 'कॉल बैक का अनुरोध',
  body: 'अपना नंबर दें। हम आपको कॉल करेंगे।',
  fullName: 'पूरा नाम',
  phone: 'फ़ोन',
  phonePlaceholder: '+91',
  languageLabel: 'भाषा',
  timeLabel: 'कॉल का सही समय',
  timeWindows: {
    now: 'जितनी जल्दी हो सके',
    morning: 'सुबह (9–12 बजे)',
    afternoon: 'दोपहर (12–4 बजे)',
    evening: 'शाम (4–8 बजे)',
  },
  topicLabel: 'विषय',
  topicPlaceholder: 'ज़रूरी नहीं, जैसे किराया एग्रीमेंट',
  consentBefore: 'मैं कॉल पाने और ',
  consentLink: 'प्राइवेसी पॉलिसी',
  consentAfter: ' से सहमत हूं।',
  consentRequired: 'आगे बढ़ने के लिए सहमति दें।',
  submit: 'कॉल का अनुरोध करें',
  busy: 'भेजा जा रहा है…',
  close: 'बंद करें',
  successTitle: 'अनुरोध मिल गया',
  success: (referenceCode) => `नंबर ${referenceCode}। हम जल्द कॉल करेंगे।`,
  duplicate: (referenceCode) => `आपका एक अनुरोध पहले से बाकी है (${referenceCode})। हम जल्द कॉल करेंगे।`,
  done: 'ठीक है',
  contactNote: 'कॉल पर बात करना चाहते हैं? हम कॉल करेंगे।',
};
