// कैटलॉग, सर्विस पेज, चेकआउट और क्लाइंट ऑर्डर
export const commerce = {
  labels: {
    productCategories: {
      property: { label: 'प्रॉपर्टी', summary: 'वेरिफिकेशन, डीड और किराया एग्रीमेंट।' },
      business: { label: 'बिज़नेस और स्टार्टअप', summary: 'कंपनी सेटअप, GST और ट्रेडमार्क।' },
      documents: { label: 'दस्तावेज़ और एग्रीमेंट', summary: 'नोटिस, एग्रीमेंट और एफिडेविट।' },
      personal: { label: 'निजी और परिवार', summary: 'वसीयत, उपभोक्ता और पारिवारिक मामले।' },
    },
    orderStatuses: {
      created: 'भुगतान बाकी',
      paid: 'भुगतान हो गया',
      failed: 'भुगतान नहीं हुआ',
      refunded: 'रिफंड हो गया',
      'partially-refunded': 'आंशिक रिफंड',
      cancelled: 'रद्द',
    },
    couponTypes: {
      percent: 'प्रतिशत छूट',
      flat: 'तय रकम की छूट',
    },
    refundStatuses: {
      pending: 'प्रक्रिया में',
      processed: 'पूरा हुआ',
      failed: 'नहीं हुआ',
    },
    languages: {
      en: 'अंग्रेज़ी',
      hi: 'हिंदी',
      bn: 'बांग्ला',
      ta: 'तमिल',
      te: 'तेलुगु',
      mr: 'मराठी',
      gu: 'गुजराती',
      kn: 'कन्नड़',
      ml: 'मलयालम',
      pa: 'पंजाबी',
    },
  },

  catalogue: {
    metadata: {
      title: 'कानूनी सेवाएं',
      description: 'तय कीमत और साफ़ समय-सीमा वाली कानूनी सेवाएं।',
    },
    header: {
      title: 'कानूनी सेवाएं',
      lead: 'तय कीमत। साफ़ समय-सीमा।',
    },
    tabsLabel: 'सेवा की श्रेणियां',
    allCategories: 'सभी',
    empty: 'यहां अभी कोई सेवा नहीं है।',
    buyNow: 'अभी खरीदें',
    getStarted: 'शुरू करें',
    wasPrice: (priceLabel) => `पहले ${priceLabel}`,
    otherHelp: {
      title: 'कुछ और चाहिए?',
      body: 'क्षेत्र चुनें और हमें बताएं।',
    },
  },

  product: {
    breadcrumb: 'सेवाएं',
    turnaroundLabel: 'समय-सीमा',
    inclusionsTitle: 'इसमें क्या शामिल है',
    documentsTitle: 'ज़रूरी दस्तावेज़',
    faqTitle: 'सवाल',
    governmentFeeLabel: 'सरकारी फीस',
    buyNow: 'अभी खरीदें',
    request: 'अनुरोध भेजें',
    buyNote: 'Razorpay से सुरक्षित भुगतान।',
    requestNote: 'काम शुरू करने से पहले फीस बताई जाएगी।',
    stickyLabel: 'यह सेवा खरीदें',
    save: (amountLabel, percent) => `${amountLabel} की बचत (${percent}% छूट)`,
    stepsTitle: "यह कैसे काम करता है",
    steps: [
      { title: "तय फीस दें", description: "सुरक्षित भुगतान। रसीद ईमेल पर।" },
      { title: "दस्तावेज़ भेजें", description: "अभी या बाद में अकाउंट से अपलोड करें।" },
      { title: "हम काम करते हैं", description: "अकाउंट में प्रगति देखें।" },
      { title: "आप तक पहुँचाया जाता है", description: "नतीजा अपने अकाउंट से डाउनलोड करें।" },
    ],
    assurances: ["हमारी इन-हाउस लीगल टीम काम करती है", "आपके दस्तावेज़ निजी रहते हैं", "काम शुरू होने से पहले रद्द करें"],
    questionsTitle: "पहले कुछ पूछना है?",
    contactLink: "हमसे बात करें",
    relatedTitle: "मिलती-जुलती सेवाएं",
  },

  checkout: {
    metadata: { title: 'चेकआउट' },
    title: 'चेकआउट',
    backToService: 'सेवा पर वापस',
    summaryTitle: 'ऑर्डर का सार',
    subtotal: 'कुल राशि',
    discount: 'छूट',
    total: 'देय राशि',
    detailsTitle: 'आपकी जानकारी',
    fullName: 'पूरा नाम',
    email: 'ईमेल',
    phone: 'फ़ोन',
    phonePlaceholder: '+91',
    languageLabel: 'पसंदीदा भाषा',
    descriptionLabel: 'हमें कुछ और बताना है?',
    descriptionHint: 'ज़रूरी नहीं। कोई तारीख या अहम बात लिखें।',
    coupon: {
      label: 'कूपन कोड',
      apply: 'लगाएं',
      applying: 'जांच हो रही है…',
      remove: 'हटाएं',
      applied: (code) => `${code} लग गया।`,
    },
    consentBefore: 'मैं ',
    consentLink: 'शर्तों',
    consentAfter: ' और प्राइवेसी पॉलिसी से सहमत हूं।',
    consentRequired: 'आगे बढ़ने के लिए सहमति दें।',
    pay: (amountLabel) => `${amountLabel} चुकाएं`,
    placeOrder: 'ऑर्डर करें',
    processing: 'प्रक्रिया जारी है…',
    secureNote: 'भुगतान Razorpay के ज़रिए होता है।',
    dismissed: 'भुगतान पूरा नहीं हुआ। आप फिर से कोशिश कर सकते हैं।',
    failed: 'भुगतान नहीं हुआ। फिर से कोशिश करें।',
    verifyFailed: 'हम भुगतान की पुष्टि नहीं कर पाए। अगर पैसे कट गए हैं, तो ऑर्डर नंबर के साथ हमसे संपर्क करें।',
    notSetUp: 'अभी ऑनलाइन भुगतान उपलब्ध नहीं है। कृपया हमसे संपर्क करें।',
    scriptFailed: 'भुगतान विंडो नहीं खुली। अपना इंटरनेट जांचें।',
    retry: 'फिर से कोशिश करें',
    orderReference: (referenceCode) => `ऑर्डर ${referenceCode}`,
  },

  success: {
    metadata: { title: 'ऑर्डर कन्फ़र्म' },
    title: 'ऑर्डर कन्फ़र्म हो गया',
    referenceLabel: 'ऑर्डर नंबर',
    requestLabel: 'अनुरोध नंबर',
    nextTitle: 'आगे क्या होगा',
    nextSteps: ['रसीद ईमेल पर भेजी जा रही है।', 'हमारी टीम आपकी जानकारी देखेगी।', 'एक प्रोफ़ेशनल काम शुरू करने के लिए संपर्क करेंगे।'],
    viewOrder: 'ऑर्डर देखें',
    browse: 'सेवाएं देखें',
  },

  orders: {
    metadataTitle: 'ऑर्डर',
    title: 'ऑर्डर',
    intro: 'आपकी खरीदी गई सेवाएं।',
    empty: 'अभी कोई ऑर्डर नहीं है।',
    emptyCta: 'सेवाएं देखें',
    meta: (referenceCode, dateLabel) => `${referenceCode}, ${dateLabel}`,
    moreItems: (count) => `+${count} और`,
  },

  orderDetail: {
    metadataTitle: 'ऑर्डर',
    breadcrumb: 'ऑर्डर',
    notFoundTitle: 'ऑर्डर नहीं मिला',
    notFoundBody: 'चेकआउट वाले ईमेल से साइन इन करें।',
    back: 'ऑर्डर पर वापस',
    meta: (referenceCode, dateLabel) => `${referenceCode}, ${dateLabel} को किया गया`,
    itemsTitle: 'सेवाएं',
    discountWithCode: (code) => `छूट (${code})`,
    refunded: 'रिफंड',
    timelineTitle: 'स्थिति',
    requestTitle: 'आपका अनुरोध',
    requestBody: (referenceCode) => `हमारी टीम अनुरोध ${referenceCode} पर काम कर रही है।`,
    viewRequest: 'अनुरोध देखें',
  },
};
