export const dashboard = {
  navLabel: 'My LexBridge',
  nav: {
    overview: 'सारांश',
    requests: 'अनुरोध',
    consultations: 'सलाह',
    documents: 'दस्तावेज़',
    profile: 'प्रोफ़ाइल',
  },

  overview: {
    metadataTitle: 'सारांश',
    welcome: (firstName) => (firstName ? `फिर से स्वागत है, ${firstName}` : 'फिर से स्वागत है'),
    intro: 'आपके अनुरोध, सलाह और दस्तावेज़।',
    activeRequests: 'चालू अनुरोध',
    allRequests: 'सभी अनुरोध',
    noActiveBefore: 'कोई चालू अनुरोध नहीं।',
    noActiveFinder: 'सही मदद खोजें',
    noActiveOr: 'या',
    noActiveContact: 'अनुरोध भेजें',
    requestMeta: (referenceCode, dateLabel) => `${referenceCode}, ${dateLabel}`,
    viewRequest: 'देखें',
    upcomingConsultation: 'अगली सलाह',
    noUpcoming: 'कोई आने वाली सलाह नहीं।',
    book: 'बुक करें',
    dateLabel: 'तारीख',
    timeLabel: 'समय',
    modeLabel: 'माध्यम',
    timeValue: (timeLabel) => `${timeLabel} IST`,
    joinVideo: 'वीडियो कॉल से जुड़ें',
    videoPending: 'कॉल से पहले वीडियो लिंक यहाँ दिखेगा।',
    viewDetails: 'विवरण',
    documentsTitle: 'दस्तावेज़',
    documentsCount: (count) => `${count} दस्तावेज़`,
    documentsDefault: 'आपके भेजे गए दस्तावेज़।',
    documentsUnavailable: 'दस्तावेज़ अभी उपलब्ध नहीं।',
    documentCentre: 'दस्तावेज़ खोलें',
    paymentsTitle: 'पेमेंट',
    paymentsBody: 'ऑनलाइन पेमेंट जल्द शुरू होगा।',
    supportTitle: 'सहायता',
    supportBody: 'किसी अनुरोध में मदद चाहिए?',
    supportCta: 'संपर्क करें',
  },

  requests: {
    metadataTitle: 'अनुरोध',
    title: 'आपके अनुरोध',
    intro: 'इस ईमेल से भेजे गए सभी अनुरोध।',
    emptyBefore: 'अभी कोई अनुरोध नहीं।',
    emptyCta: 'अनुरोध भेजें',
  },

  requestDetail: {
    metadataTitle: 'अनुरोध',
    notFoundTitle: 'अनुरोध नहीं मिला',
    notFoundBody: 'रेफ़रेंस जाँचें या उसी ईमेल से साइन इन करें।',
    backToRequests: 'अनुरोधों पर वापस',
    breadcrumb: 'अनुरोध',
    meta: (referenceCode, dateLabel) => `${referenceCode}, ${dateLabel} को भेजा`,
    updates: 'अपडेट',
    description: 'आपने क्या बताया',
    documents: 'दस्तावेज़',
    noDocuments: 'इस अनुरोध के लिए कोई दस्तावेज़ नहीं।',
    shareTitle: 'दस्तावेज़ भेजें',
  },

  consultations: {
    metadataTitle: 'सलाह',
    title: 'सलाह',
    book: 'बुक करें',
    upcoming: 'आने वाली',
    noUpcoming: 'कोई आने वाली सलाह नहीं।',
    past: 'पिछली और कैंसिल',
    when: (dayLabel, timeLabel, minutes, modeLabel) => `${dayLabel}, ${timeLabel} IST, ${minutes} मिनट, ${modeLabel}`,
    reference: (referenceCode) => `रेफ़ ${referenceCode}`,
    joinVideo: 'वीडियो कॉल से जुड़ें',
    videoPending: 'कॉल से पहले वीडियो लिंक यहाँ दिखेगा।',
    phoneNote: 'तय समय पर हम आपको कॉल करेंगे।',
    cancel: 'कैंसिल करें',
    confirmLabel: 'कैंसिल की पुष्टि',
    confirmBody: 'यह सलाह कैंसिल करें?',
    confirmYes: 'हाँ, कैंसिल करें',
    confirmBusy: 'कैंसिल हो रहा है…',
    confirmNo: 'रहने दें',
    tooLateBefore: (hours) => `${hours} घंटे से कम बचे हैं। बदलने के लिए `,
    tooLateLink: 'हमसे संपर्क करें',
    tooLateAfter: '।',
  },

  documents: {
    metadataTitle: 'दस्तावेज़',
    title: 'दस्तावेज़',
    intro: 'इन्हें सिर्फ़ आप और आपके मामले की टीम देख सकती है।',
    yourDocuments: 'आपके दस्तावेज़',
    empty: 'अभी कोई दस्तावेज़ नहीं।',
    referenceOption: (referenceCode, label) => `${referenceCode}: ${label}`,
  },

  profile: {
    metadataTitle: 'प्रोफ़ाइल',
    title: 'प्रोफ़ाइल',
    intro: 'इससे हमारी टीम आप तक पहुँच पाती है।',
    fullName: 'पूरा नाम',
    phone: 'फ़ोन',
    phonePlaceholder: '+91',
    emailLabel: 'ईमेल',
    emailNote: 'इसी से साइन इन होता है, इसलिए इसे यहाँ नहीं बदल सकते।',
    saved: 'प्रोफ़ाइल सेव हो गई।',
    save: 'सेव करें',
    saving: 'सेव हो रहा है…',
  },
};
