export const forms = {
  serviceRequest: {
    fullName: 'पूरा नाम',
    email: 'ईमेल',
    phone: 'फ़ोन',
    phonePlaceholder: '+91',
    service: 'सेवा',
    servicePlaceholder: 'सेवा चुनें',
    subtypePlaceholder: 'एक चुनें',
    descriptionLabel: 'आपकी ज़रूरत',
    descriptionPlaceholder: 'संक्षेप में बताइए…',
    descriptionHint: 'कोई डेडलाइन या सुनवाई की तारीख हो तो लिखें।',
    consentBefore: 'मैं ',
    consentLink: 'प्राइवेसी पॉलिसी',
    consentAfter: ' से सहमत हूँ। LexBridge लॉ फ़र्म नहीं है।',
    submit: 'अनुरोध भेजें',
    submitting: 'भेज रहे हैं…',
    stepsLabel: "प्रगति",
    stepMatter: "आपका मामला",
    stepDetails: "आपकी जानकारी",
    stepStatus: (current, total, name) => `चरण ${current}/${total}: ${name}`,
    continue: "आगे बढ़ें",
    back: "पीछे",
    stepErrors: {
      service: "सेवा चुनें।",
      description: "थोड़ा और विस्तार से लिखें (कम से कम 20 अक्षर)।",
    },
    successTitle: 'अनुरोध मिल गया',
    successReferenceBefore: 'रेफ़रेंस: ',
    successReferenceAfter: '। पुष्टि आपके ईमेल पर भेजी जा रही है।',
    successNextBefore: 'इसकी स्थिति ',
    successNextLink: 'My LexBridge',
    successNextAfter: ' में उसी ईमेल से देखें।',
    successNextNoAccounts: 'हमारी टीम जल्द संपर्क करेगी।',
  },

  upload: {
    title: 'दस्तावेज़ अपलोड करें',
    submit: 'अपलोड करें',
    busy: 'अपलोड हो रहा है…',
    relatedRequest: 'संबंधित अनुरोध',
    notLinked: 'किसी से जुड़ा नहीं',
    fileLabel: 'फ़ाइल',
    fileHint: (maxSizeLabel) => `PDF, JPG, PNG या DOCX, ${maxSizeLabel} तक।`,
    chooseFile: 'फ़ाइल चुनें।',
    wrongType: 'PDF, JPG, PNG या DOCX फ़ाइल चुनें।',
    tooLarge: (maxSizeLabel) => `फ़ाइल ${maxSizeLabel} तक की हो सकती है।`,
    chooseRequest: 'संबंधित अनुरोध चुनें।',
    uploaded: (fileName) => `${fileName} अपलोड हो गई।`,
  },

  documentList: {
    empty: 'अभी कोई दस्तावेज़ नहीं।',
    typeLabels: {
      'application/pdf': 'PDF',
      'image/jpeg': 'JPG',
      'image/png': 'PNG',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document': 'Word',
    },
    fallbackType: 'फ़ाइल',
    uploadedOn: (dateLabel) => `${dateLabel} को अपलोड`,
    sharedByTeam: 'LexBridge ने भेजा',
    forReference: (referenceCode) => `${referenceCode} के लिए`,
    download: 'डाउनलोड',
  },

  timeline: {
    empty: 'अभी कोई अपडेट नहीं।',
  },

  fieldErrors: {
    FullName: 'अपना पूरा नाम लिखें।',
    Email: 'सही ईमेल लिखें।',
    Phone: 'सही फ़ोन नंबर लिखें।',
    ServiceCategory: 'सेवा चुनें।',
    Description: 'थोड़ा और विस्तार से बताइए।',
    ConsentGiven: 'आगे बढ़ने के लिए सहमति दें।',
    Code: '6 अंकों का कोड लिखें।',
    Messages: '1 से 500 के बीच संख्या लिखें।',
    Reason: 'कारण लिखें।',
    Title: 'शीर्षक लिखें।',
    Topic: 'विषय चुनें।',
    Summary: 'सारांश छोटा रखें।',
    Slug: 'छोटे अक्षरों वाले शब्द, बीच में हाइफ़न।',
    Body: 'लेख का टेक्स्ट लिखें।',
  },
  checkFields: 'कृपया हाइलाइट किए गए फ़ील्ड देखें।',
};
