// Labels for the intake catalog (packages/shared/src/intakeCatalog.js): subtype names, the
// conditional questions each subtype asks, and every option value. Keys must mirror the catalog
// and stay key-identical with the English file (checked by scripts/checkI18nKeys.mjs).
export const intake = {
  detailsTitle: 'मामले की जानकारी',
  subtypeLabel: 'मामला किस तरह का है?',
  otherLabel: 'कुछ और',
  choose: 'चुनें…',
  fieldRequired: 'कृपया यह प्रश्न भरें।',
  topicTitle: 'परामर्श किस विषय पर है?',
  topicIntro: 'कुछ छोटे प्रश्न, ताकि हम आपको सही वकील से मिला सकें।',
  categoryLabel: 'कानून का क्षेत्र',
  categoryPlaceholder: 'क्षेत्र चुनें…',

  subtypes: {
    'property-dispute': { label: 'संपत्ति विवाद' },
    'landlord-tenant': { label: 'मकान मालिक–किरायेदार' },
    'title-verification': { label: 'टाइटल जाँच' },
    'defective-product': { label: 'खराब उत्पाद' },
    'deficient-service': { label: 'घटिया सेवा' },
    'refund-dispute': { label: 'रिफंड विवाद' },
    'cheque-bounce': { label: 'चेक बाउंस' },
    'fir-bail': { label: 'एफ़आईआर / जमानत' },
    'cyber-crime': { label: 'साइबर अपराध' },
    'employment-contract': { label: 'नौकरी का अनुबंध' },
    'vendor-contract': { label: 'विक्रेता अनुबंध' },
    nda: { label: 'एनडीए (गोपनीयता समझौता)' },
    'rental-agreement': { label: 'किराया अनुबंध' },
    'company-incorporation': { label: 'कंपनी पंजीकरण' },
    'compliance-notice': { label: 'अनुपालन नोटिस' },
    'legal-notice': { label: 'कानूनी नोटिस' },
    agreement: { label: 'अनुबंध' },
    affidavit: { label: 'शपथ पत्र' },
    application: { label: 'आवेदन' },
    complaint: { label: 'शिकायत' },
    'other-document': { label: 'अन्य दस्तावेज़' },
    'document-review': { label: 'दस्तावेज़ समीक्षा' },
    'general-advice': { label: 'सामान्य सलाह' },
    'case-opinion': { label: 'केस पर राय' },
    'document-consultation': { label: 'दस्तावेज़ परामर्श' },
    other: { label: 'कुछ और' },
  },

  fields: {
    propertyType: { label: 'संपत्ति का प्रकार' },
    disputeNature: { label: 'विवाद किस बारे में है?' },
    propertyCity: { label: 'संपत्ति किस शहर में है' },
    opposingPartyKnown: { label: 'क्या दूसरे पक्ष की जानकारी है?' },
    amountAtStake: { label: 'राशि कितनी है?' },
    yourRole: { label: 'आप मकान मालिक हैं या किरायेदार?' },
    issue: { label: 'समस्या क्या है?' },
    agreementExists: { label: 'क्या लिखित अनुबंध है?' },
    purpose: { label: 'यह किस उद्देश्य के लिए है?' },
    productType: { label: 'क्या उत्पाद है?' },
    vendorName: { label: 'विक्रेता या ब्रांड का नाम' },
    complaintFiledBefore: { label: 'पहले शिकायत की है?' },
    serviceType: { label: 'कौन-सी सेवा?' },
    providerName: { label: 'सेवा देने वाले का नाम' },
    whatRefund: { label: 'रिफंड किस बाबत है?' },
    sellerType: { label: 'खरीद कहाँ से की?' },
    chequeAmount: { label: 'चेक की राशि' },
    chequeDate: { label: 'चेक की तारीख' },
    bankName: { label: 'बैंक का नाम' },
    noticeSent: { label: 'कानूनी नोटिस भेजा गया है?' },
    daysSinceDishonour: { label: 'चेक बाउंस को कितना समय हुआ?' },
    firRegistered: { label: 'क्या एफ़आईआर दर्ज है?' },
    policeStation: { label: 'थाना' },
    offenceType: { label: 'किस आरोप/अपराध की बात है?' },
    custodyStatus: { label: 'हिरासत की स्थिति' },
    fraudType: { label: 'धोखाधड़ी का प्रकार' },
    amountLost: { label: 'कितनी राशि का नुकसान' },
    platform: { label: 'ऐप, वेबसाइट या प्लेटफ़ॉर्म' },
    roleLevel: { label: 'पद का स्तर' },
    contractStage: { label: 'अनुबंध की स्थिति' },
    employerType: { label: 'नियोक्ता का प्रकार' },
    valueRange: { label: 'अनुबंध की राशि' },
    entityType: { label: 'संस्था का प्रकार' },
    foundersCount: { label: 'संस्थापकों की संख्या' },
    authority: { label: 'कौन-सा विभाग?' },
    noticeType: { label: 'नोटिस में क्या कहा गया है?' },
    responseDeadline: { label: 'जवाब की अंतिम तिथि' },
    noticeAgainst: { label: 'नोटिस किसके विरुद्ध है?' },
    noticeMatter: { label: 'नोटिस किस बाबत है?' },
    agreementType: { label: 'कौन-सा अनुबंध?' },
    partiesCount: { label: 'कितने पक्ष हैं?' },
    language: { label: 'भाषा' },
    affidavitPurpose: { label: 'शपथ पत्र किस बाबत है?' },
    applicationTo: { label: 'आवेदन किसे करना है?' },
    applicationMatter: { label: 'आवेदन किस बाबत है?' },
    complaintAgainst: { label: 'शिकायत किसके विरुद्ध है?' },
    forum: { label: 'कहाँ दायर होगी?' },
    documentDescription: { label: 'दस्तावेज़ का विवरण' },
    documentType: { label: 'दस्तावेज़ का प्रकार' },
    matterArea: { label: 'कानून का क्षेत्र' },
    urgency: { label: 'कितनी जल्दी चाहिए?' },
    deadline: { label: 'अंतिम तिथि (यदि कोई हो)' },
    topicArea: { label: 'यह केस किस क्षेत्र का है?' },
    caseStage: { label: 'केस किस चरण में है' },
    documentCount: { label: 'कितने दस्तावेज़ हैं?' },
  },

  options: {
    residential: 'आवासीय',
    commercial: 'वाणिज्यिक',
    agricultural: 'कृषि भूमि',
    plot: 'प्लॉट / ज़मीन',
    'title-ownership': 'टाइटल या स्वामित्व',
    partition: 'सह-मालिकों में बँटवारा',
    encroachment: 'अतिक्रमण',
    possession: 'कब्ज़ा',
    'builder-delay': 'बिल्डर की देरी',
    yes: 'हाँ',
    no: 'नहीं',
    'under-1-lakh': '₹1 लाख से कम',
    '1-10-lakh': '₹1–10 लाख',
    '10-lakh-1-crore': '₹10 लाख – ₹1 करोड़',
    'above-1-crore': '₹1 करोड़ से अधिक',
    'under-10k': '₹10,000 से कम',
    '10k-1-lakh': '₹10,000 – ₹1 लाख',
    'above-10-lakh': '₹10 लाख से अधिक',
    landlord: 'मकान मालिक',
    tenant: 'किरायेदार',
    'rent-default': 'किराया नहीं दिया जा रहा',
    eviction: 'निकालने (बेदखली) की कार्रवाई',
    'deposit-refund': 'सिक्योरिटी जमा राशि वापसी',
    'repair-dispute': 'मरम्मत / रख-रखाव',
    buying: 'खरीदने के लिए',
    selling: 'बेचने के लिए',
    loan: 'लोन लेने के लिए',
    inheritance: 'विरासत',
    builder: 'बिल्डर / रियल एस्टेट',
    insurance: 'बीमा',
    banking: 'बैंकिंग',
    transport: 'ट्रांसपोर्ट / कूरियर',
    telecom: 'दूरसंचार / इंटरनेट',
    online: 'ऑनलाइन',
    offline: 'कोई दुकान',
    both: 'ऑनलाइन और ऑफ़लाइन दोनों',
    'under-30': '30 दिन से कम',
    '30-90': '30–90 दिन',
    'over-90': '90 दिन से अधिक',
    'not-arrested': 'किसी की गिरफ़्तारी नहीं',
    'in-custody': 'कोई हिरासत में है',
    released: 'जमानत पर रिहा',
    'online-payment-fraud': 'ऑनलाइन भुगतान धोखाधड़ी',
    'job-scam': 'नकली नौकरी ऑफ़र',
    'investment-scam': 'निवेश घोटाला',
    'identity-theft': 'पहचान की चोरी',
    junior: 'प्रारंभिक स्तर',
    mid: 'मध्यम स्तर',
    senior: 'वरिष्ठ स्तर',
    leadership: 'नेतृत्व स्तर',
    'offer-received': 'ऑफ़र मिला, हस्ताक्षर नहीं',
    signed: 'हस्ताक्षर हो चुका है',
    'working-under-it': 'इसी अनुबंध में काम कर रहा हूँ',
    startup: 'स्टार्टअप',
    company: 'स्थापित कंपनी',
    government: 'सरकारी / PSU',
    foreign: 'विदेशी नियोक्ता',
    drafting: 'अभी बन रहा है',
    'received-for-review': 'मिल गया, समीक्षा चाहिए',
    hiring: 'किसी कर्मचारी के लिए',
    vendor: 'विक्रेता या सप्लायर के लिए',
    investor: 'निवेशक के लिए',
    partnership: 'साझेदारी',
    1: '1',
    2: '2',
    '3-plus': '3 या अधिक',
    '2-5': '2–5',
    'more-than-5': '5 से अधिक',
    'pvt-ltd': 'प्राइवेट लिमिटेड',
    llp: 'एलएलपी',
    opc: 'वन पर्सन कंपनी',
    gst: 'जीएसटी',
    'income-tax': 'आयकर',
    roc: 'कंपनी रजिस्ट्रार',
    labour: 'श्रम विभाग',
    'payment-due': 'बकाया भुगतान',
    property: 'संपत्ति',
    consumer: 'उपभोक्ता विवाद',
    employment: 'रोज़गार',
    english: 'अंग्रेज़ी',
    hindi: 'हिंदी',
    bilingual: 'द्विभाषी (अंग्रेज़ी + हिंदी)',
    'consumer-commission': 'उपभोक्ता आयोग',
    police: 'पुलिस',
    court: 'अदालत',
    notice: 'नोटिस',
    'court-papers': 'अदालती काग़ज़ात',
    agreement: 'अनुबंध',
    'employment-contract': 'नौकरी का अनुबंध',
    'rental-agreement': 'किराया अनुबंध',
    family: 'पारिवारिक',
    business: 'व्यापारिक',
    criminal: 'आपराधिक',
    normal: 'जल्दी नहीं है',
    'this-week': 'एक सप्ताह के भीतर',
    urgent: 'बहुत ज़रूरी',
    'notice-received': 'नोटिस मिला है',
    'case-filed': 'केस दायर हो चुका है',
    'hearing-ongoing': 'सुनवाई चल रही है',
    appeal: 'अपील',
    other: 'अन्य',
  },
};
